services:
  - type: web
    name: student-application-app
    runtime: python
    rootDir: src/student-application-app
    buildCommand: python -m pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false