services:
  - type: web
    name: nptel-admin-portal
    runtime: node
    rootDir: nptel-admin-portal
    buildCommand: npm install && npm run build
    startCommand: npx next start -p $PORT -H 0.0.0.0
    healthCheckPath: /
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true

  - type: web
    name: student-application-app
    runtime: python
    rootDir: src/student-application-app
    buildCommand: python -m pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        generateValue: true