services:
  - type: web
    name: student-application-app
    runtime: python
    rootDir: src/student-application-app
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true